# Generated by Django 2.2.17 on 2021-03-03 17:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_key',
            field=models.CharField(blank=True, max_length=128, verbose_name='Ключ подтверждения'),
        ),
        migrations.AddField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 17, 7, 22, 790654, tzinfo=utc), verbose_name='Актуальность ключа'),
        ),
    ]
