# Generated by Django 2.2.17 on 2021-03-18 16:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_create_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 20, 16, 59, 48, 660469, tzinfo=utc), verbose_name='Актуальность ключа'),
        ),
    ]
