# Generated by Django 2.2.17 on 2021-03-18 18:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_auto_20210318_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 20, 18, 9, 4, 501367, tzinfo=utc), verbose_name='Актуальность ключа'),
        ),
    ]
