# Generated by Django 2.2.17 on 2021-03-23 19:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_auto_20210318_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 19, 10, 21, 882954, tzinfo=utc), verbose_name='Актуальность ключа'),
        ),
    ]
