# Generated by Django 2.2.17 on 2021-03-23 19:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_auto_20210323_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 19, 38, 5, 443915, tzinfo=utc), verbose_name='Актуальность ключа'),
        ),
    ]
