# Generated by Django 2.2.17 on 2021-03-31 18:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_auto_20210323_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 18, 1, 59, 227829, tzinfo=utc), verbose_name='Актуальность ключа'),
        ),
    ]
